"""
AERIS-TWIN 7 Colab Notebook Generator
Generates valid nbformat v4 Jupyter Notebooks for Google Colab compatibility:
- 00_AERIS_TWIN_Master_Training.ipynb
- 01_CylinderHeadML_Training.ipynb
- 02_ExhaustML_Training.ipynb
- 03_TurboIntakeML_Training.ipynb
- 04_CrankcaseML_Training.ipynb
- 05_OilSumpML_Training.ipynb
- 06_PropGearboxML_Training.ipynb
"""

import os
import json

def make_notebook(title, description, model_name=None):
    cells = []

    # Title & Markdown intro
    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            f"# {title}\n",
            f"**AERIS-TWIN Engine Digital Twin Machine Learning Pipeline**\n\n",
            f"{description}\n\n",
            "> **Synthetic Data Warning**: These models are trained and evaluated on physics-informed synthetic telemetry generated by the AERIS-TWIN simulation engine. They are prototype digital twin models and are NOT certified for real aircraft operation."
        ]
    })

    # Cell 1: Environment Setup
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Step 1: Install Dependencies\n",
            "!pip install -q scikit-learn pandas numpy matplotlib joblib\n\n",
            "import os\n",
            "import json\n",
            "import math\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "import joblib\n",
            "from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier\n",
            "from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error\n",
            "print('Environment Ready!')"
        ]
    })

    # Cell 2: Dataset Loading & Train/Val/Test Split
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Step 2: Load Physics-Informed Engine Dataset\n",
            "dataset_url = 'https://raw.githubusercontent.com/AERIS-TWIN/twin-vision/main/ml/data/engine_telemetry_dataset.csv'\n",
            "# Fallback to local dataset file if running locally\n",
            "csv_path = 'ml/data/engine_telemetry_dataset.csv' if os.path.exists('ml/data/engine_telemetry_dataset.csv') else dataset_url\n",
            "print(f'Loading dataset from {csv_path}...')\n",
            "df = pd.read_csv(csv_path)\n",
            "train_df = df[df['split'] == 'train']\n",
            "val_df = df[df['split'] == 'val']\n",
            "test_df = df[df['split'] == 'test']\n",
            "print(f'Dataset Split -> Train: {len(train_df)} | Val: {len(val_df)} | Test: {len(test_df)}')"
        ]
    })

    if model_name:
        # Subsystem notebook specific training logic
        cells.append({
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                f"# Step 3: Train {model_name} Model\n",
                "if '" + model_name + "' == 'CylinderHeadML':\n",
                "    features = ['obs_rpm', 'throttle', 'coolant_flow_lmin', 'ambient_temp', 'altitude', 'air_density_ratio', 'obs_map', 'iat_celsius', 'res_cht2']\n",
                "    targets = ['obs_cht1', 'obs_cht2', 'obs_cht3', 'obs_cht4', 'thermal_stress', 'overheat_risk']\n",
                "elif '" + model_name + "' == 'ExhaustML':\n",
                "    features = ['obs_rpm', 'obs_map', 'throttle', 'obs_cht1', 'obs_cht2', 'res_egt1', 'ambient_temp', 'air_density_ratio']\n",
                "    targets = ['obs_egt1', 'obs_egt2', 'obs_egt3', 'obs_egt4', 'runner_balance', 'combustion_eff', 'injector_risk']\n",
                "elif '" + model_name + "' == 'TurboIntakeML':\n",
                "    features = ['altitude', 'baro_pressure_kpa', 'air_density_ratio', 'iat_celsius', 'throttle', 'obs_rpm', 'obs_map', 'res_boost']\n",
                "    targets = ['true_turbo_rpm', 'true_boost', 'compressor_eff', 'wastegate_risk']\n",
                "elif '" + model_name + "' == 'CrankcaseML':\n",
                "    features = ['obs_vib_rms', 'dominant_freq', 'bpfo_peak', 'obs_rpm', 'engine_hours', 'res_vib']\n",
                "    targets = ['structural_health', 'bearing_fatigue', 'estimated_rul']\n",
                "elif '" + model_name + "' == 'OilSumpML':\n",
                "    features = ['obs_oil_temp', 'obs_oil_press', 'obs_rpm', 'engine_hours', 'oil_age_hours', 'ambient_temp', 'throttle']\n",
                "    targets = ['viscosity_idx', 'lubrication_risk']\n",
                "else:\n",
                "    features = ['prop_rpm', 'prop_vib', 'gearbox_temp', 'engine_hours', 'obs_vib_rms', 'throttle', 'res_vib']\n",
                "    targets = ['gear_wear_idx', 'gear_pitting_risk']\n\n",
                "X_train, y_train = train_df[features].values, train_df[targets].values\n",
                "X_test, y_test = test_df[features].values, test_df[targets].values\n\n",
                "model = RandomForestRegressor(n_estimators=30, max_depth=12, random_state=42)\n",
                "model.fit(X_train, y_train)\n",
                "y_pred = model.predict(X_test)\n\n",
                "r2 = r2_score(y_test, y_pred)\n",
                "mae = mean_absolute_error(y_test, y_pred)\n",
                "print(f'Test R² Score: {r2:.4f}')\n",
                "print(f'Test MAE: {mae:.4f}')"
            ]
        })

        # Cell 4: Save & Reload Model Artifact Verification
        cells.append({
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                f"# Step 4: Serialize & Verify Model Artifact\n",
                f"os.makedirs('ml/artifacts/{model_name}', exist_ok=True)\n",
                f"art_path = 'ml/artifacts/{model_name}/model.joblib'\n",
                "joblib.dump(model, art_path)\n",
                "print(f'Saved artifact -> {art_path}')\n\n",
                "# Reload and run inference verification\n",
                "reloaded_model = joblib.load(art_path)\n",
                "sample_input = X_test[:1]\n",
                "pred_sample = reloaded_model.predict(sample_input)\n",
                "print('Sample Inference Output:', pred_sample[0])"
            ]
        })

    else:
        # Master Notebook Pipeline Execution
        cells.append({
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Step 3: Run Master 6-Model Training Pipeline\n",
                "subsystems = [\n",
                "    ('CylinderHeadML', ['obs_rpm', 'throttle', 'coolant_flow_lmin', 'ambient_temp', 'altitude', 'air_density_ratio', 'obs_map', 'iat_celsius', 'res_cht2'], ['obs_cht1', 'obs_cht2', 'obs_cht3', 'obs_cht4', 'thermal_stress', 'overheat_risk']),\n",
                "    ('ExhaustML', ['obs_rpm', 'obs_map', 'throttle', 'obs_cht1', 'obs_cht2', 'res_egt1', 'ambient_temp', 'air_density_ratio'], ['obs_egt1', 'obs_egt2', 'obs_egt3', 'obs_egt4', 'runner_balance', 'combustion_eff', 'injector_risk']),\n",
                "    ('TurboIntakeML', ['altitude', 'baro_pressure_kpa', 'air_density_ratio', 'iat_celsius', 'throttle', 'obs_rpm', 'obs_map', 'res_boost'], ['true_turbo_rpm', 'true_boost', 'compressor_eff', 'wastegate_risk']),\n",
                "    ('CrankcaseML', ['obs_vib_rms', 'dominant_freq', 'bpfo_peak', 'obs_rpm', 'engine_hours', 'res_vib'], ['structural_health', 'bearing_fatigue', 'estimated_rul']),\n",
                "    ('OilSumpML', ['obs_oil_temp', 'obs_oil_press', 'obs_rpm', 'engine_hours', 'oil_age_hours', 'ambient_temp', 'throttle'], ['viscosity_idx', 'lubrication_risk']),\n",
                "    ('PropGearboxML', ['prop_rpm', 'prop_vib', 'gearbox_temp', 'engine_hours', 'obs_vib_rms', 'throttle', 'res_vib'], ['gear_wear_idx', 'gear_pitting_risk'])\n",
                "]\n\n",
                "results = {}\n",
                "for name, feats, targs in subsystems:\n",
                "    X_tr, y_tr = train_df[feats].values, train_df[targs].values\n",
                "    X_te, y_te = test_df[feats].values, test_df[targs].values\n",
                "    m = RandomForestRegressor(n_estimators=30, max_depth=12, random_state=42)\n",
                "    m.fit(X_tr, y_tr)\n",
                "    preds = m.predict(X_te)\n",
                "    r2 = r2_score(y_te, preds)\n",
                "    mae = mean_absolute_error(y_te, preds)\n",
                "    results[name] = {'r2': round(float(r2), 4), 'mae': round(float(mae), 4)}\n",
                "    os.makedirs(f'ml/artifacts/{name}', exist_ok=True)\n",
                "    joblib.dump(m, f'ml/artifacts/{name}/model.joblib')\n",
                "    print(f'[TRAINED] {name} -> R²: {r2:.4f}, MAE: {mae:.4f}')"
            ]
        })

    nb = {
        "cells": cells,
        "metadata": {
            "colab": {"provenance": []},
            "language_info": {"name": "python"},
        },
        "nbformat": 4,
        "nbformat_minor": 2
    }
    return nb

def main():
    os.makedirs("ml/notebooks", exist_ok=True)
    notebooks = [
        ("00_AERIS_TWIN_Master_Training.ipynb", "AERIS-TWIN Master 6-Subsystem Digital Twin Training Pipeline", None),
        ("01_CylinderHeadML_Training.ipynb", "CylinderHeadML Subsystem Training Pipeline", "CylinderHeadML"),
        ("02_ExhaustML_Training.ipynb", "ExhaustML Subsystem Training Pipeline", "ExhaustML"),
        ("03_TurboIntakeML_Training.ipynb", "TurboIntakeML Subsystem Training Pipeline", "TurboIntakeML"),
        ("04_CrankcaseML_Training.ipynb", "CrankcaseML Subsystem Training Pipeline", "CrankcaseML"),
        ("05_OilSumpML_Training.ipynb", "OilSumpML Subsystem Training Pipeline", "OilSumpML"),
        ("06_PropGearboxML_Training.ipynb", "PropGearboxML Subsystem Training Pipeline", "PropGearboxML"),
    ]

    for filename, title, model in notebooks:
        path = os.path.join("ml/notebooks", filename)
        nb_json = make_notebook(title, f"Training & validation notebook for {title}.", model)
        with open(path, "w") as f:
            json.dump(nb_json, f, indent=2)
        print(f"[NOTEBOOK GENERATED] {path}")

if __name__ == "__main__":
    main()
